#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path


DEFAULT_SOURCE_DIR = Path("/home/littlegirl112/workspace/comp/atcoder")
DEFAULT_OUTPUT_PATH = Path("src/acl-headers.js")


def collect_headers(source_dir: Path) -> dict[str, str]:
    headers: dict[str, str] = {}
    for path in sorted(source_dir.iterdir()):
        if not path.is_file():
            continue
        if path.suffix not in {"", ".hpp"}:
            continue
        headers[f"atcoder/{path.name}"] = path.read_text(encoding="utf-8")
    return headers


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    args = parser.parse_args()

    headers = collect_headers(args.source_dir.resolve())
    payload = json.dumps(headers, ensure_ascii=False, indent=2, sort_keys=True)
    text = (
        "// Generated by scripts/build_acl_bundle.py\n"
        f"export const ACL_HEADERS = {payload};\n"
    )
    args.output.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
