#!/usr/bin/env python3

from __future__ import annotations

import json
import urllib.request
from pathlib import Path

BASE_URL = "https://raw.githubusercontent.com/not522/ac-library-python/master/atcoder/"
FILES = [
    "__init__.py",
    "_bit.py",
    "_math.py",
    "_scc.py",
    "convolution.py",
    "dsu.py",
    "fenwicktree.py",
    "lazysegtree.py",
    "math.py",
    "maxflow.py",
    "mincostflow.py",
    "modint.py",
    "scc.py",
    "segtree.py",
    "string.py",
    "twosat.py",
]
OUTPUT_PATH = Path("src/python-acl-modules.js")


def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as response:
        return response.read().decode("utf-8")


def main() -> None:
    modules = {}
    for filename in FILES:
        module_name = f"atcoder.{filename[:-3]}" if filename != "__init__.py" else "atcoder"
        modules[module_name] = fetch_text(BASE_URL + filename)

    payload = json.dumps(modules, ensure_ascii=False, indent=2)
    OUTPUT_PATH.write_text(
        "// Generated by scripts/build_python_acl_bundle.py\n"
        f"export const PYTHON_ACL_MODULES = {payload};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
