#!/usr/bin/env python3

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

BASE_URL = "https://raw.githubusercontent.com/rust-lang-ja/ac-library-rs/master/src/"
FILES = [
    "convolution.rs",
    "dsu.rs",
    "fenwicktree.rs",
    "internal_bit.rs",
    "internal_math.rs",
    "internal_queue.rs",
    "internal_scc.rs",
    "internal_type_traits.rs",
    "lazysegtree.rs",
    "lib.rs",
    "math.rs",
    "maxflow.rs",
    "mincostflow.rs",
    "modint.rs",
    "scc.rs",
    "segtree.rs",
    "string.rs",
    "twosat.rs",
]
OUTPUT_PATH = Path("src/rust-acl-bundle.js")
OUTPUT_HEADER = "//https://github.com/rust-lang-ja/ac-library-rs"
OUTPUT_LIST_ALL = [
    "convolution",
    "dsu",
    "fenwicktree",
    "lazysegtree",
    "math",
    "maxflow",
    "mincostflow",
    "modint",
    "scc",
    "segtree",
    "string",
    "twosat",
    "internal_bit",
    "internal_math",
    "internal_queue",
    "internal_scc",
    "internal_type_traits",
]
DEPENDENCY_LIST = {
    "convolution": ["internal_bit", "modint"],
    "lazysegtree": ["internal_bit", "segtree"],
    "math": ["internal_math"],
    "maxflow": ["internal_type_traits", "internal_queue"],
    "mincostflow": ["internal_type_traits"],
    "modint": ["internal_math"],
    "scc": ["internal_scc"],
    "segtree": ["internal_bit", "internal_type_traits"],
    "twosat": ["internal_scc"],
}


def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as response:
        return response.read().decode("utf-8")


def parse_symbol_map(lib_rs: str) -> dict[str, str]:
    symbol_map: dict[str, str] = {}
    current_module: str | None = None

    for raw_line in lib_rs.splitlines():
        line = raw_line.strip()
        if line.startswith("pub use "):
            match = re.match(r"pub use ([a-z_][a-z0-9_]*)::(.*)", line)
            if not match:
                continue
            current_module = match.group(1)
            remainder = match.group(2)
        elif current_module is not None:
            remainder = line
        else:
            continue

        done = remainder.endswith(";")
        remainder = remainder.rstrip(";").strip()
        if remainder.startswith("{"):
            remainder = remainder[1:]
        if remainder.endswith("}"):
            remainder = remainder[:-1]
        remainder = remainder.strip()

        if remainder:
            for symbol in remainder.split(","):
                name = symbol.strip()
                if name:
                    symbol_map[name] = current_module

        if done:
            current_module = None

    return symbol_map


def main() -> None:
    files = {filename: fetch_text(BASE_URL + filename) for filename in FILES}
    lib_rs = files["lib.rs"]
    payload = {
        "header": OUTPUT_HEADER,
        "outputListAll": OUTPUT_LIST_ALL,
        "dependencyList": DEPENDENCY_LIST,
        "symbolMap": parse_symbol_map(lib_rs),
        "files": {
            filename[:-3]: files[filename].rstrip("\n")
            for filename in FILES
            if filename.endswith(".rs") and filename != "lib.rs"
        },
    }
    OUTPUT_PATH.write_text(
        "// Generated by scripts/build_rust_acl_bundle.py\n"
        f"export const RUST_ACL_BUNDLE = {json.dumps(payload, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
